plugin:
  config-version: 1
  debug: false
  enabled-auto-updater: false
  permission: "jsonic.use"
  enabled-http: true
  max-threads: 2
  http-request-timeout-seconds: 30
  http-connect-timeout-seconds: 10

json:
  path-delimiter: "."
  path-token-cache-size: 1024
  watcher:
    interval: 100
    refresh-rate: 50

server:
  enabled: true
  port: 8080
  host: "127.0.0.1"
  public-bind: false
  max-body-size: 1mb
  thread-model: main
  https:
    enabled: false
    port: 8443
    cert-file: "certs/server.pem"
    key-file: "certs/server.key"
    key-password: ""
  middleware:
    cors: true
    logger: true
    json: false
